export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_CURRENT_CLINIC = 'SET_CURRENT_CLINIC';

export const FETCH_MEMBERS_START = 'FETCH_MEMBERS_START';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAIL = 'FETCH_MEMBERS_FAIL';

export const JOIN_CLINIC_START = 'JOIN_CLINIC_START';
export const JOIN_CLINIC_SUCCESS = 'JOIN_CLINIC_SUCCESS';
export const JOIN_CLINIC_FAIL = 'JOIN_CLINIC_FAIL';

export const ADD_CLINIC = 'ADD_CLINIC';

export const CREATE_STAFF_START = 'CREATE_STAFF_START';
export const CREATE_STAFF_SUCCESS = 'CREATE_STAFF_SUCCESS';
export const CREATE_STAFF_FAIL = 'CREATE_STAFF_FAIL';

export const ADD_STAFF_START = 'ADD_STAFF_START';
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS';
export const ADD_STAFF_FAIL = 'ADD_STAFF_FAIL';

export const FETCH_SUPERVISIONS_START = 'FETCH_SUPERVISIONS_START';
export const FETCH_SUPERVISIONS_SUCCESS = 'FETCH_SUPERVISIONS_SUCCESS';
export const FETCH_SUPERVISIONS_FAIL = 'FETCH_SUPERVISIONS_FAIL';
